##############################################################################
## Provision my-new-apb-2
## This role executes much of the needed functionality to provision an
## application using an Ansible Playbook Bundle.  Included in the comments
## below are some sample resources for getting started deploying an application
## to OpenShift.
##############################################################################


##############################################################################
## An OpenShift Origin deployment configuration provides a replication
## controller, spins up pods, and also provides the ability to transition from
## one deployment of an image to a new one.
## https://docs.openshift.org/latest/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations
##############################################################################
- name: create deployment config
  openshift_v1_deployment_config:
    name: "{{ app_name }}"
    namespace: '{{ namespace }}'
    labels:
      app: my-new-apb-2
      service: my-new-apb-2
    replicas: 1
    selector:
      app: my-new-apb-2
      service: my-new-apb-2
    spec_template_metadata_labels:
      app: my-new-apb-2
      service: my-new-apb-2
    containers:
    - env:
      image: docker.io/ansibleplaybookbundle/hello-world:latest # replace with your application image
      name: my-new-apb-2
      ports:
      - container_port: 8080
        protocol: TCP


##############################################################################
## A Kubernetes service serves as an internal load balancer.  It identifies a
## set of replicated pods in order to proxy the connections it receives to them.
## https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#services
##############################################################################
#- name: create my-new-apb-2 service
#  k8s_v1_service:
#    name: my-new-apb-2
#    namespace: '{{ namespace }}'
#    labels:
#      app: my-new-apb-2
#      service: my-new-apb-2
#    selector:
#      app: my-new-apb-2
#      service: my-new-apb-2
#    ports:
#      - name: web
#        port: 80
#        target_port: 8080


##############################################################################
## An OpenShift Origin route exposes a service at a host name, so that external
## clients can reach it by name. Each route consists of a name, a service
## selector, and an optional security configuration.
## https://docs.openshift.org/latest/architecture/networking/routes.html
##############################################################################
#- name: create my-new-apb-2 route
#  openshift_v1_route:
#    name: my-new-apb-2
#    namespace: '{{ namespace }}'
#    labels:
#      app: my-new-apb-2
#      service: my-new-apb-2
#    to_name: my-new-apb-2
#    spec_port_target_port: web


